language: generic
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
    - os: windows
addons:
  apt:
    update: true
    packages:
#       clang-6.0
      clang-7
      llvm-7
  homebrew:
    update: true
    packages:
      - watchman
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install python2 7zip
        where 7z
        export PATH=$PATH:"/C/Python27"
        wget -N http://ftp.mozilla.org/pub/mozilla.o...tup-Latest.zip
        7z x -aoa MozillaBuildSetup-Latest.zip -omozilla-build
        cd repo; rm `find . -name 'config.cache'`;
        travis_retry wget -q https://ftp.mozilla.org/pub/mozilla.org/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe
        travis_wait 30 ./MozillaBuildSetup-Latest /?
        travis_wait 30 ./MozillaBuildSetup-Latest /S
        python /V
        python hello.py
        ;;
      osx)
        python hello.py
        ;;
      linux)
        sudo apt-get purge -y llvm-6.0 clang-6.0
        python hello.py
        ;;
    esac
install:
- travis_wait 30 python ./python/mozboot/bin/bootstrap.py --application-choice=browser --vcs git --no-interactive | tail -n 500
script: 
  - travis_wait 90 ./mach build -v
