dist: bionic
env:
  - SCCACHE_VERSION=0.2.12 SHELL=/bin/bash
before_install:
  >-
    sudo apt-get -y install
    libssl-dev
    pkg-config
    python
    rustc
install:
- python ./python/mozboot/bin/bootstrap.py --application-choice=browser --vcs git --no-interactive
- cargo install sccache --version $SCCACHE_VERSION || echo "Reusing sccache from CI cache"
script: 
  - ./mach build -v
