language: generic
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
    - os: windows
addons:
  apt:
    update: true
    packages:
      clang-6.0
      llvm-6.0
  homebrew:
    update: true
    packages:
      - watchman
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install python2 7zip.install
        ls /C/Python27
        export PATH=$PATH:"/C/Python27"
        where python*
        where 7zip*
        where C:\Python27
        wget -q https://ftp.mozilla.org/pub/mozilla.org/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe
        MozillaBuildSetup-Latest.exe
        python -V
        python hello.py
        ;;
#       osx)
#         cat /etc/issue
#         ;;
      linux)
        cat /etc/issue
        ;;
    esac
install:
- python ./python/mozboot/bin/bootstrap.py --application-choice=browser --vcs git --no-interactive
script: 
  - ./mach build -v
