language: generic
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
    - os: windows
addons:
  apt:
    update: true
    packages:
#       clang-6.0
      clang-7
      llvm-7
  homebrew:
    update: true
    packages:
      - watchman
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install python2
        pwd
        ls /C/Python27
        export PATH=$PATH:"/C/Python27"
        wget -q https://ftp.mozilla.org/pub/mozilla.org/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe
        MozillaBuildSetup-Latest.exe
        python -V
        python hello.py
        ;;
      osx)
        python hello.py
        ;;
      linux)
        apt-get purge -y llvm-6.0 clang-6.0
        python hello.py
        ;;
    esac
install:
- python ./python/mozboot/bin/bootstrap.py --application-choice=browser --vcs git --no-interactive
script: 
  - ./mach build -v
