language: generic
jobs:
  include:
    - os: linux
      dist: bionic
      env: SCCACHE_VERSION=0.2.12
    - os: osx
    - os: windows
env:
  - 
addons:
  apt:
    update: true
    packages:
      cargo
      libssl-dev
      pkg-config
      python
      rustc
before_install:
  - export PATH=$PATH:/home/travis/.cargo/bin/sccache
install:
- cargo install sccache --version $SCCACHE_VERSION || echo "Reusing sccache from CI cache"
- python ./python/mozboot/bin/bootstrap.py --application-choice=browser --vcs git --no-interactive
script: 
  - ./mach build -v
