language: generic
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
    - os: windows
addons:
  apt:
    update: true
    packages:
      - clang
  homebrew:
    update: true
    packages:
      - cask
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install python2
        ;;
      osx)
        brew install wget
        ;;
      linux)
        cat /etc/issue
        ;;
    esac
install:
- python ./python/mozboot/bin/bootstrap.py --application-choice=browser --vcs git --no-interactive
script: 
  - ./mach build -v
