dist: bionic
env:
  - SCCACHE_VERSION=0.2.12
  - SHELL=/bin/bash
before_install:
  >-
    sudo apt-get -y install
    alsa
    clang
    libssl-dev
    pkg-config
    python
    rustc
    autoconf2.13 build-essential nodejs python-dev python-pip python-setuptools unzip uuid zip
install:
- cargo install sccache --version $SCCACHE_VERSION || echo "Reusing sccache from CI cache"
script: 
  - ./mach build -v
