dist: bionic
language: bash
env:
  - SCCACHE_VERSION=0.2.12 SHELL=/bin/bash
before_install:
  >-
    sudo apt-get -y install
    cargo
    libssl-dev
    pkg-config
    python
    rustc
install:
- cargo install sccache --version $SCCACHE_VERSION || echo "Reusing sccache from CI cache"
- python ./python/mozboot/bin/bootstrap.py --application-choice=browser --vcs git --no-interactive
script: 
  - ./mach build -v
