language: generic
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
    - os: windows
addons:
  apt:
    update: true
  homebrew:
    update: true
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install python2
        ls /C/Python27
        export PATH=$PATH:"/C/Python27"
        where /?
        wget -q https://ftp.mozilla.org/pub/mozilla.org/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe
        MozillaBuildSetup-Latest.exe
        python2 hello.py
        ;;
      osx)
        brew install wget
        ;;
      linux)
        cat /etc/issue
        ;;
    esac
install:
- python ./python/mozboot/bin/bootstrap.py --application-choice=browser --vcs git --no-interactive
script: 
  - ./mach build -v
